Style core elements
brenoxav/awesome-books pull request #5
Opened 2021-07-07 20:42 UTC by disc3110

Add style to the page using bootstrap

2021-07-07 22:17 UTC, umararshadbut requested changes
Hi @disc3110 and @brenoxav , 

Good job so far :+1:!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
HAPPY CODING :computer:
**Umair Arshad**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-07-07 22:17 UTC, umararshadbut commented on index.html
>      </div>
Make sure that this section is align-center according to the [wireframe](https://github.com/microverseinc/curriculum-javascript/blob/bb245ca8a9d3bb04ebefbbd45e800764e1fc5f74/books/images/awesome_books_core_elements.png). And make sure that the book title, writer name and remove button should be in the same row.

2021-07-07 22:42 UTC, brenoxav commented
Hello, @umararshadbut!
Thank you for your review.

The link to the live demo was wrong.
We have already fixed that.

Please, [check the correct link.](http://brenoxavier.com/awesome-books/)

2021-07-08 01:34 UTC, voscarmv approved these changes
Hi @disc3110 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-07-08 14:54 UTC, merged